language: go
sudo: false
go:
  - 1.4.3
  - 1.5.3
install:
  - go get -v github.com/qedus/osmpbf
  - go get -v golang.org/x/tools/cmd/cover
script:
  - go test -v -covermode=count -coverprofile=profile.cov
after_success:
  - go get -v github.com/mattn/goveralls
  - export PATH=$PATH:$HOME/gopath/bin
  - goveralls -coverprofile=profile.cov -service=travis-ci
